# Apriori Implementation

In [51]:
import numpy as np 
import pandas as pd 
from mlxtend.frequent_patterns import apriori, association_rules

In [52]:
df = pd.read_excel('./Online Retail.xlsx') 
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [53]:
df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [54]:
df.Country.value_counts()

Country
United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: count, dtype: int64

In [55]:
null_values_count = df.isnull().sum()
print("Number of null values in each column:")
print(null_values_count)

Number of null values in each column:
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [56]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [57]:
df = df[df.Country == 'United Kingdom']

In [58]:
null_values_count = df.isnull().sum()
print("Number of null values in each column:")
print(null_values_count)

Number of null values in each column:
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     133600
Country             0
dtype: int64

In [59]:
df = df.dropna(subset=['Description'])

In [60]:
null_values_count = df.isnull().sum()
print("Number of null values in each column:")
print(null_values_count)

Number of null values in each column:
InvoiceNo           0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     132146
Country             0
dtype: int64

In [61]:
qtt = df['Quantity'].unique()
print(qtt)

[     6      8      2     32      3      4     80     48     64     10
     12    120     24     96     23      5      1     36     -1     50
     40    100    192    432    144    288    -12    -24     16     20
      9    128     25     30     28      7     72    200    600    480
     -6     14     18     -2     11     33     13     70    252     60
    216    384     27     15     22     19     17     21     34     47
    108     52     -4  -9360     -3     75    270     42    240     90
    320   1824    204     69    -36   -192   -144    160   2880   1400
     39    -48    -50     56     26     31     82     78     97     98
     35    -30     -8    720    -20    156    324     38     37     49
     95     -5     -9     -7    -11     29     41    -10    -72    -35
    -43    402    378    150    300     54    104     67    258     66
     44     55     46     99     61    408    972    208   1008   1000
    -25    250   1394    400    110    -14    -13    -33   -723   -100
    272     84    -47    -18    -96    -15    113     45    106     68
    267    115     65   1728    -60    -16     53     76     71     43
    213     58    576   2400    500    -80    180   -300   -500    -23
    752    960   1296    210    172     57     79    215    129    138
    116    135    197   -106   -150    147    256    168    -40    -29
  -2600   -990   -290    860   1010   1356   1284    186    114   1930
   2000   3114   1300    670    111    211     59   -310    648     62
  74215 -74215     89  -1400    -17     73    -57    -21    -32   -120
    112    456    -59    900   -600    -42    -94   -207    130   2592
    420    800    101   1200    864     94  -1430   -162   -230   -390
    504    123    -76   -200    -64   1056   1500    280    141    124
   -741   3906   -400    360    102   1152    198     86   -720    125
    228   -154  -3000     81    -19   -675   -210   -345   -975  -1200
  -1121    -27   -541  -1277   -197   3000  -1100    -63  -5368   -259
   -178    170   -110    176     88    700   -102   2160   -323   -450
   -232   -524  -2472    -49    342    304    175    220     74     93
    164    163     63    117    637    122    158    165    118   1440
    350   -690    -39    -46     83    312    392    -26  -1479   -576
   -750    330    151    -93   -432    -58   -670  -1300  -1930  -2000
  -3114    462    -65    -68    492    -53    273  -1512     85    -51
     51   -360    105   -960   -240  -2376   1350    428  -1350   -160
    336   -786   -590    132   -413   -664    227   2700    222    246
    906    756    888    552    -97    224    738    608   -212   4300
    146    143    276    -52   -125   -140   -108   4000   -304   -272
  -1206    -95   1600    323   -161    -84   -618   -204    -22   1515
  -1515  -9058  -9600    660   -420   -220   -271  -1440    264    188
    588    612    152   -324   -480   -164   -118    430  -1681     87
    155    701    828    768    540    696    560   -250   -408    121
   -124    512   -251  -3100   3100    -37    126    291   3186    140
    -28    -75    109   -121   -227    261    352    142  -1060   -342
    -90    348   1900    157    968    684    824   -828   -701    196
    248    410    236    230    145   -109   -252   -334   -318   -126
   -113   -180    840   -967   -203   -156   -443  -1897   -434    -38
   -484   -635    450    310    494   -384    -44   1788    624    744
    416    496    396    306   1878   1944    666    708   1428    852
   1412    528   -756   -752   -152    -85    -34   -312    -79    -31
   -288   -131    183   -186    -82    -70   -231   -458  -2880   1540
   -130    672   -800   -430    -45   -380    -74    -61   -840  -1296
   -365   -270   -306     91    255    468   -468   -168    -71   -111
    -78   -184   -103   -335     92   4800    -66   -112  -1000    -77
   1992    136    -54    184   -138    148   -657  -1671  -1158  -2618
  -2003   -674  -4830   -905  -1128    -67    232    832    992    630
   1020   2100    162    -62   -104  -1560  -1284    -81    314    370
    131    133    484    149    153    257    139    137    628    245
    171    179   1820    478    335    253    242    375   -276   -256
    225    281    193    181    404    244    207    199   1130    326
    654    688    268    249   -864   -117    234  -1510   -550    -92
   -244   -234   -132    -41   -209   -327    219   -313    279   -398
   -280    374   -170   -504   -696   -101    -56   -149   -224   -428
   -179    212   -267   -175  12540    760    -98    774   -145   -153
  -1131   -135   1120     77    -73   -900    177    490    388    620
   1404   -155   -355    -55    -87   -337  -1050   -338    205   -235
    698  80995 -80995]

In [62]:
# some spaces are there in description; need to remove else later operation it will create problem..
df['Description'] = df['Description'].str.strip()

In [63]:
#some of transaction quantity is negative which can not be possible remove them.
df = df[df.Quantity >0]

In [64]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541889,581585,22466,FAIRY TALE COTTAGE NIGHT LIGHT,12,2011-12-09 12:31:00,1.95,15804.0,United Kingdom
541890,581586,22061,LARGE CAKE STAND HANGING STRAWBERY,8,2011-12-09 12:49:00,2.95,13113.0,United Kingdom
541891,581586,23275,SET OF 3 HANGING OWLS OLLIE BEAK,24,2011-12-09 12:49:00,1.25,13113.0,United Kingdom
541892,581586,21217,RED RETROSPOT ROUND CAKE TINS,24,2011-12-09 12:49:00,8.95,13113.0,United Kingdom
541893,581586,20685,DOORMAT RED RETROSPOT,10,2011-12-09 12:49:00,7.08,13113.0,United Kingdom

In [65]:
distinct_values_count = df['InvoiceNo'].nunique()
print(distinct_values_count)

18194

In [66]:
distinct_values_count = df['StockCode'].nunique()
distinct_values_count

3919

In [67]:
df['Description']

0          WHITE HANGING HEART T-LIGHT HOLDER
1                         WHITE METAL LANTERN
2              CREAM CUPID HEARTS COAT HANGER
3         KNITTED UNION FLAG HOT WATER BOTTLE
4              RED WOOLLY HOTTIE WHITE HEART.
                         ...
541889         FAIRY TALE COTTAGE NIGHT LIGHT
541890    LARGE CAKE STAND  HANGING STRAWBERY
541891       SET OF 3 HANGING OWLS OLLIE BEAK
541892          RED RETROSPOT ROUND CAKE TINS
541893                  DOORMAT RED RETROSPOT
Name: Description, Length: 485694, dtype: object

In [68]:
basket = (df[df['Country'] =="United Kingdom"] 
          .groupby(['InvoiceNo', 'Description'])['Quantity'] 
          .sum().unstack().reset_index().fillna(0) 
          .set_index('InvoiceNo')) 
# Defining the hot encoding function to make the data suitable  
# for the concerned libraries 
def hot_encode(x): 
    if(x<= 0): 
        return 0
    if(x>= 1): 
        return 1

In [69]:
basket.shape
basket

Description,*Boombox Ipod Classic,*USB Office Mirror Ball,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 DAISY PEGS IN WOOD BOX,12 EGG HOUSE PAINTED WOOD,12 HANGING EGGS HAND PAINTED,12 IVORY ROSE PEG PLACE SETTINGS,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,...,returned,taig adjust,test,to push order througha s stock was,website fixed,wrongly coded 20713,wrongly coded 23343,wrongly marked,wrongly marked 23343,wrongly sold (22719) barcode
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536365,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536366,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536367,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536368,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536369,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581585,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581586,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A563185,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A563186,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A563187,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [70]:
basket_encoded = basket.map(hot_encode) 
basket = basket_encoded

In [71]:
basket.head()

Description,*Boombox Ipod Classic,*USB Office Mirror Ball,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 DAISY PEGS IN WOOD BOX,12 EGG HOUSE PAINTED WOOD,12 HANGING EGGS HAND PAINTED,12 IVORY ROSE PEG PLACE SETTINGS,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,...,returned,taig adjust,test,to push order througha s stock was,website fixed,wrongly coded 20713,wrongly coded 23343,wrongly marked,wrongly marked 23343,wrongly sold (22719) barcode
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536365,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536366,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536367,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536368,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536369,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [72]:
# means 3 times in total number of transaction the item should be present.
frequent_itemsets = apriori(basket, min_support=0.03, use_colnames=True)

/home/meriem-mk/.local/lib/python3.11/site-packages/mlxtend/frequent_patterns/fpcommon.py:110: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [73]:
frequent_itemsets

      support                                           itemsets
0    0.046994                           (6 RIBBONS RUSTIC CHARM)
1    0.031934                  (60 CAKE CASES VINTAGE CHRISTMAS)
2    0.041387                      (60 TEATIME FAIRY CAKE CASES)
3    0.030505                   (72 SWEETHEART FAIRY CAKE CASES)
4    0.048148                       (ALARM CLOCK BAKELIKE GREEN)
..        ...                                                ...
135  0.036111  (JUMBO SHOPPER VINTAGE RED PAISLEY, JUMBO BAG ...
136  0.038364  (JUMBO BAG RED RETROSPOT, JUMBO STORAGE BAG SUKI)
137  0.033363  (LUNCH BAG  BLACK SKULL., LUNCH BAG RED RETROS...
138  0.030450  (LUNCH BAG RED RETROSPOT, LUNCH BAG PINK POLKA...
139  0.030010  (PINK REGENCY TEACUP AND SAUCER, ROSES REGENCY...

[140 rows x 2 columns]

In [74]:
rules_mlxtend = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules_mlxtend

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(ALARM CLOCK BAKELIKE RED),(ALARM CLOCK BAKELIKE GREEN),0.051116,0.048148,0.030944,0.605376,12.573307,0.028483,2.412051,0.970051
1,(ALARM CLOCK BAKELIKE GREEN),(ALARM CLOCK BAKELIKE RED),0.048148,0.051116,0.030944,0.642694,12.573307,0.028483,2.655663,0.967027
2,(PINK REGENCY TEACUP AND SAUCER),(GREEN REGENCY TEACUP AND SAUCER),0.038639,0.051336,0.031714,0.820768,15.988282,0.029730,5.292945,0.975132
3,(GREEN REGENCY TEACUP AND SAUCER),(PINK REGENCY TEACUP AND SAUCER),0.051336,0.038639,0.031714,0.617773,15.988282,0.029730,2.515157,0.988183
4,(GREEN REGENCY TEACUP AND SAUCER),(ROSES REGENCY TEACUP AND SAUCER),0.051336,0.052600,0.038529,0.750535,14.268798,0.035829,3.797733,0.980238
5,(ROSES REGENCY TEACUP AND SAUCER),(GREEN REGENCY TEACUP AND SAUCER),0.052600,0.051336,0.038529,0.732497,14.268798,0.035829,3.546374,0.981546
6,(JUMBO BAG BAROQUE BLACK WHITE),(JUMBO BAG RED RETROSPOT),0.050016,0.106519,0.031329,0.626374,5.880414,0.026001,2.391377,0.873640
7,(JUMBO BAG RED RETROSPOT),(JUMBO BAG BAROQUE BLACK WHITE),0.106519,0.050016,0.031329,0.294118,5.880414,0.026001,1.345810,0.928888
8,(JUMBO BAG PINK POLKADOT),(JUMBO BAG RED RETROSPOT),0.063702,0.106519,0.043146,0.677308,6.358587,0.036361,2.768837,0.900069
9,(JUMBO BAG RED RETROSPOT),(JUMBO BAG PINK POLKADOT),0.106519,0.063702,0.043146,0.405057,6.358587,0.036361,1.573760,0.943201
10,(JUMBO SHOPPER VINTAGE RED PAISLEY),(JUMBO BAG RED RETROSPOT),0.062273,0.106519,0.036111,0.579876,5.443897,0.029478,2.126711,0.870518
11,(JUMBO BAG RED RETROSPOT),(JUMBO SHOPPER VINTAGE RED PAISLEY),0.106519,0.062273,0.036111,0.339009,5.443897,0.029478,1.418669,0.913626
12,(JUMBO BAG RED RETROSPOT),(JUMBO STORAGE BAG SUKI),0.106519,0.062108,0.038364,0.360165,5.798977,0.031749,1.465834,0.926215
13,(JUMBO STORAGE BAG SUKI),(JUMBO BAG RED RETROSPOT),0.062108,0.106519,0.038364,0.617699,5.798977,0.031749,2.337116,0.882358
14,(LUNCH BAG BLACK SKULL.),(LUNCH BAG RED RETROSPOT),0.066835,0.076509,0.033363,0.499178,6.524452,0.028249,1.843950,0.907375
15,(LUNCH BAG RED RETROSPOT),(LUNCH BAG BLACK SKULL.),0.076509,0.066835,0.033363,0.436063,6.524452,0.028249,1.654733,0.916880
16,(LUNCH BAG RED RETROSPOT),(LUNCH BAG PINK POLKADOT),0.076509,0.055293,0.030450,0.397989,7.197816,0.026219,1.569251,0.932406
17,(LUNCH BAG PINK POLKADOT),(LUNCH BAG RED RETROSPOT),0.055293,0.076509,0.030450,0.550696,7.197816,0.026219,2.055381,0.911467
18,(PINK REGENCY TEACUP AND SAUCER),(ROSES REGENCY TEACUP AND SAUCER),0.038639,0.052600,0.030010,0.776671,14.765684,0.027977,4.242181,0.969746
19,(ROSES REGENCY TEACUP AND SAUCER),(PINK REGENCY TEACUP AND SAUCER),0.052600,0.038639,0.030010,0.570533,14.765684,0.027977,2.238497,0.984035

In [75]:
rules_mlxtend.to_csv('./test.csv')
rules = pd.read_csv('./test.csv')